### ISSUE TITLE
Unable to build the source code -- getting errors on vlc library dependency

### ISSUE THREAD

**Issue by hatimjohar** [inspiredtechnologies/IP-Camera-Emulator#2]
Hi,

I am trying to build this IP-Camera-Emulator source code however getting errors for VLC library missing

I saw one line in readme for this
"To build the RtspStreamerLib DLL, you will need the VLC SDK C++ headers and 32-bit MSVC libraries"

Can you point me guide / steps that can help me build this and I have also downloaded the source code from https://github.com/RSATom/libvlc-sdk but don't know next steps on the same.

Please help to build the same.

Thanks,
Hatim

**Comment by inspiredtechnologies** [comment]
Dear Hatim,

In the source code from https://github.com/RSATom/libvlc-sdk, the VLC SDK C++ headers can be found in the "include" subfolder and the 32-bit MSVC libraries in the "lib\msvc" subfolder. You just need to specify where the compiler can find those paths on your machine.

If you're using Visual Studio, try these,
- Open the Properties page for the RtspStreamerLib project
- Select "VC++ Directories"
- In "Include Directories", add the path to libvlc-sdk\include
- In "Library Directories", add the path to libvlc-sdk\lib\msvc

If for whatever reason it still refuses to compile, you could use a precompiled copy of the RtspStreamerLib.dll from the IP Camera Emulator Standard repository (https://github.com/inspiredtechnologies/IP-Camera-Emulator-Standard), and exclude the RtspStreamerLib project from your build configuration.

**Comment by hatimjohar** [comment]
Thank you team inspiredtechnologies for detailed response with steps.

I tried to do the same as mentioned using Visual Studio 2013, however still facing link errors. even I downloaded the dll from the url shared and again tried it is failing.

We will try it and let you know. Thanks appreciate your response.

**Comment by inspiredtechnologies** [comment]
Closing issue as there's been no further updates
